# Generated by Django 4.2.2 on 2023-07-29 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist_category_comment_alter_user_id_watchlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
