# Generated by Django 4.2.2 on 2023-08-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlist_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auction_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_auction', to='auctions.auctionlist'),
        ),
    ]
